"""Typed interfaces for cross-service interactions."""
from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol

from gi.repository import Gtk


class NotesManagerProtocol(Protocol):
    """Any storage backend that can read/write notes."""

    def get_notes(self, search_text: str = "") -> list[str]: ...
    def read_note(self, name: str) -> str: ...
    def save_note(self, name: str, content: str) -> None: ...
    def create_note(self, name: str = "Untitled", content: str = "") -> str: ...
    def delete_note(self, name: str) -> None: ...
    def rename_note(self, old_name: str, new_name: str) -> bool: ...
    def update_checkbox(self, note_name: str, line_num: int, checked: bool) -> bool: ...
    def update_deadline(self, note_name: str, line_num: int, new_deadline: str | None) -> bool: ...
    def get_all_checkboxes(self, exclude: set[str] | None = None) -> list[dict[str, Any]]: ...


class ConfigManagerProtocol(Protocol):
    """Any config backend that persists/app preferences."""

    pinned: set[str]
    archived: set[str]

    def get(self, key: str, fallback: Any = None) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def pin(self, note_name: str) -> None: ...
    def unpin(self, note_name: str) -> None: ...
    def is_archived(self, note_name: str) -> bool: ...
    def toggle_archive(self, note_name: str) -> None: ...
    def remove_note(self, note_name: str) -> None: ...
    def flush_immediate(self) -> None: ...


# Simple forward-declared callback aliases used by subsystems.
RefreshListCallback = Callable[[str], None]
ShowDialogCallback = Callable[[str, str, bool], None]
